version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  status-checker:
    lang: python3-http
    handler: ./status-checker
    image: jinfanti/status-checker:latest
    build:
      copy_extra:
        - depot