version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  daily-fetcher:
    lang: python3-http
    handler: ./daily-fetcher
    image: jinfanti/daily-fetcher:latest
    schedule: "0 8 * * *"
    environment:
      gateway_url: "http://gateway.openfaas:8080/"